patchpilot:
  version: 0.9.5-alpha
  namespace: patchpilot
  image:
    strategy: registry
    dockerHubRepo: linit01/patchpilot
    tag: 0.9.5-alpha
    pullPolicy: Always
  dockerHub:
    username: linit01
    token: dckr_pat_REDACTED
  network:
    hostname: patchpilot.apps.lan
    additionalHostnames: []
    tls:
      enabled: false
      clusterIssuer: letsencrypt-prod
      secretName: ''
    httpsRedirect: true
    securityHeaders: true
    ingressClass: traefik
  certManager:
    createClusterIssuer: true
    email: ''
    challengeType: dns01-cloudflare
    cloudflare:
      email: ''
      apiTokenSecretName: cloudflare-api-token-secret
  postgres:
    user: patchpilot
    password: ''
    database: patchpilot
    storageSize: 5Gi
    storageClass: app-data
  app:
    encryptionKey: ''
    autoRefreshInterval: 60
    defaultSshUser: root
    defaultSshPort: 22
    backupRetainCount: 3
    maxBackupSizeMb: 500
  storage:
    type: local
    storageClass: nfs-backups
    backupsSize: 10Gi
    ansibleSize: 1Gi
    nfsServer: ''
    nfsShare: ''
  ansible:
    playbookPath: ''
    inventoryPath: ''
