---
apiVersion: v1
kind: Namespace
metadata:
  name: ${PP_NAMESPACE}
  labels:
    app.kubernetes.io/name: patchpilot
    app.kubernetes.io/version: "${PP_VERSION}"
    app.kubernetes.io/managed-by: patchpilot-installer
